### PR TITLE
Reworked the token display options

### PR DESCRIPTION
**Pull request by ddbrown30**
Added support for row and circular positioning

### CODE REVIEW

**Comment by ddbrown30** [comment]
circular

**Review by SalieriC — COMMENTED** [review]
Even though the code is original, I think we should credit the module with the original idea in the readmes mentions section. From my understanding it originally comes from this module: https://foundryvtt.com/packages/pf2e-dorako-ui

No objections otherwise.

**Comment by ddbrown30** [comment]
The module that was mentioned in the issue is https://foundryvtt.com/packages/status-halo. I'm fine either way if you want to credit them but the idea of circular distribution isn't exactly groundbreaking, as illustrated by the fact that you found the wrong module when searching for it.

If you add a credit, please be sure that it's listed as an inspiration credit only, as I used no code from the other module and I'm pretty sure my version doesn't even work the same as theirs.

**Comment by SalieriC** [comment]
Dig a little deeper and you'll find that status halo got its idea from the PF module I've mentioned: https://gitlab.com/mxzf/status-halo#credits

**Comment by ddbrown30** [comment]
Feel free to credit them then.

**Pull request merged**
